### PR TITLE
Numbers block

### PR DESCRIPTION
**Pull request by emp3ror**

### CODE REVIEW

**Comment by hardfire** [comment]
@emp3ror this looks amazing. can we make the following changes?

1. restrict the width so that it doesnt take whole screen space - maybe have a static background - what do you think @nepdud ?
2. in mobile view, hide blocks that don't have any numbers

**Comment by emp3ror** [comment]
> @emp3ror this looks amazing. can we make the following changes?
> 
>     1. restrict the width so that it doesnt take whole screen space - maybe have a static background - what do you think @nepdud ?
> 
>     2. in mobile view, hide blocks that don't have any numbers
Didnt get first issue. mockup has full width

for #2, when hiding block with no numbers, colored block get merged and look not so good

**Comment by hardfire** [comment]
@emp3ror regarding 1 i pushed some changes. about 2 what can we do?
also, i think some format or something that you use has totally reformatted the css file, which means that we will have merge hell now :(

**Comment by hardfire** [comment]
made some more changes @emp3ror @nepdud . Once this looks ok, i will try to see how to merge this :man_facepalming:

**Pull request merged**
